name: fuel_economy
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  hive: ^2.0.4
  uuid: ^3.0.4
  bloc: ^7.0.0
  flutter_bloc: ^7.1.0
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.0
  build_runner: ^2.1.1
  flutter_datetime_picker: ^1.5.1
  flutter_launcher_icons: ^0.9.1
  firebase_core: "^1.6.0"
  firebase_crashlytics: ^2.2.1
  firebase_performance: "^0.7.1"
  firebase_analytics: "^8.3.2"

dev_dependencies:
  flutter_test:
    sdk: flutter

# In order to update icon after modifying, run the command:
# flutter packages pub run flutter_launcher_icons:main 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/car_icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/car_icon.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
